
USE TestDB1
CREATE TABLE BASELOC_115514(SLNO INT IDENTITY(1000,1) PRIMARY KEY, BASELOC VARCHAR(30) NOT NULL UNIQUE)

INSERT INTO BASELOC_115514 VALUES('Chandigarh')
 INSERT INTO BASELOC_115514 VALUES('Trivandrum')
 INSERT INTO BASELOC_115514 VALUES('Mangalore')
INSERT INTO BASELOC_115514 VALUES('Bangalore')
INSERT INTO BASELOC_115514 VALUES('Hyderabad')
INSERT INTO BASELOC_115514 VALUES('Pune')
INSERT INTO BASELOC_115514 VALUES('Chennai')
INSERT INTO BASELOC_115514 VALUES('Bhubhaneshwar')

--drop table EMPLOY_DETAILS_115514
CREATE TABLE EMPLOY_DETAILS_115514(EMPID INT PRIMARY KEY, 
									EMPNAME VARCHAR(25) NOT NULL, 
									JOBBAND CHAR(1) NOT NULL, 
									BASELOC VARCHAR(30) REFERENCES BASELOC_115514(BASELOC) NOT NULL,
									SALERY DECIMAL)

INSERT INTO EMPLOY_DETAILS_115514 VALUES(115527,'JACK','D','Bhubhaneshwar',NULL)
INSERT INTO EMPLOY_DETAILS_115514 VALUES(115528,'JACK1','D','Trivandrum',NULL)
INSERT INTO EMPLOY_DETAILS_115514 VALUES(115529,'JACK2','D','Mangalore',NULL)
INSERT INTO EMPLOY_DETAILS_115514 VALUES(115530,'JACK3','D','Chennai',NULL)
INSERT INTO EMPLOY_DETAILS_115514 VALUES(115531,'JACK4','D','Bangalore',NULL)



CREATE TABLE SALDETAILS_115514(EMPID INT PRIMARY KEY REFERENCES EMPLOY_DETAILS_115514(EMPID), 
									EMPNAME VARCHAR(25) NOT NULL, 
									JOBBAND CHAR(1) NOT NULL, 
									BASELOC VARCHAR(30) REFERENCES BASELOC_115514(BASELOC) NOT NULL,
									SALERY DECIMAL)

--stored procedure------------
--RETURN EMPLOY DETAILS BY TAKING EMPLOY ID AS INPUT
CREATE PROCEDURE RETEMPDETAILS(@EMPID INT, 
									@EMPNAME VARCHAR(25) OUTPUT, 
									@JOBBAND CHAR(1) OUTPUT, 
									@BASELOC VARCHAR(30) OUTPUT,
									@STATUS INT OUTPUT)
AS
BEGIN
SET @STATUS = 1
IF EXISTS (SELECT * FROM EMPLOY_DETAILS_115514 WHERE EMPID=@EMPID)
BEGIN
	SET @STATUS = 0
	SELECT @EMPNAME = EMPNAME,@JOBBAND = JOBBAND, @BASELOC = BASELOC FROM EMPLOY_DETAILS_115514 WHERE EMPID=@EMPID
END
END


declare @EMPNAME VARCHAR(25), @JOBBAND CHAR(1), @BASELOC VARCHAR(30), @STATUS INT
exec RETEMPDETAILS 115527, @EMPNAME output, @JOBBAND output, @BASELOC output, @STATUS output
select @EMPNAME, @JOBBAND, @BASELOC, @STATUS


--PROCEDURE TO SAVE SALARY DETAILS....

alter PROCEDURE savedetails(@EMPID INT, 
									@EMPNAME VARCHAR(25), 
									@JOBBAND CHAR(1), 
									@BASELOC VARCHAR(30),
									@SALaRY DECIMAL,
									@STATUS INT OUTPUT)
AS
BEGIN
SET @STATUS = 1
IF EXISTS (SELECT * FROM SALDETAILS_115514 WHERE EMPID=@EMPID)
BEGIN
SET @STATUS = 1
END
ELSE
BEGIN
SET @STATUS = 0
INSERT INTO SALDETAILS_115514 VALUES(@EMPID,@EMPNAME, @JOBBAND, @BASELOC,@SALARY)
END
END

--------------------------------------------------------------------------------------------
alter PROCEDURE savedetails(@EMPID INT, 
									@EMPNAME VARCHAR(25), 
									@JOBBAND CHAR(1), 
									@BASELOC VARCHAR(30),
									@SALaRY DECIMAL,
									@STATUS INT OUTPUT)
AS
BEGIN
SET @STATUS = 1
IF EXISTS (SELECT * FROM EMPLOY_DETAILS_115514 WHERE EMPID=@EMPID)
BEGIN
IF EXISTS (SELECT * FROM SALDETAILS_115514 WHERE EMPID=@EMPID)
begin
SET @STATUS = 1
end

else
begin
SET @STATUS = 0
INSERT INTO SALDETAILS_115514 VALUES(@EMPID,@EMPNAME, @JOBBAND, @BASELOC,@SALARY)
update EMPLOY_DETAILS_115514 set SALERY = @SALaRY
end

END
ELSE
BEGIN
SET @STATUS = 0
INSERT INTO EMPLOY_DETAILS_115514 VALUES(@EMPID,@EMPNAME, @JOBBAND, @BASELOC,@SALARY)
INSERT INTO SALDETAILS_115514 VALUES(@EMPID,@EMPNAME, @JOBBAND, @BASELOC,@SALARY)
END
END


ALTER PROCEDURE RETEMPID(@EMPID INT OUTPUT)
AS
BEGIN
IF EXISTS (SELECT * FROM EMPLOY_DETAILS_115514)
BEGIN
	SELECT @EMPID = MAX(EMPID)+1 FROM EMPLOY_DETAILS_115514
END
ELSE
BEGIN
   SET @EMPID = 1000
END
return @EMPID
END

DECLARE @Y INT
EXEC RETEMPID @Y OUTPUT
SELECT @Y